name: .msbuild48

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh
    - name: Build
      run: msbuild /p:Configuration=Release OpenSim.sln     

    - uses: actions/upload-artifact@v3
      with:
          name: OpenSimLastBuild
          path: |
            bin/
            ThirdPartyLicenses/
            ThirdPartyLicenses
            README.md
            CONTRIBUTORS.txt
                      
