name: .msbuild48

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh
    - name: Build
      run: msbuild /p:Configuration=Release OpenSim.sln     

    - name: release
      run: zip -r LastBuild.zip bin ThirdPartyLicenses README.md CONTRIBUTORS.txt
    - name: shortsha 
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - uses: softprops/action-gh-release@v1
      with:
          tag_name: ${SHORT_SHA}
          name: OpenSimLastBuild
          files: LastBuild.zip
                   
