name: .msbuild48

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh
    - name: Build
      run: msbuild /p:Configuration=Release OpenSim.sln     
    - name: store
    - uses: actions/upload-artifact@v3
      with:
          name: OpenSimLastBuild
          path: |
            path/output/bin/
            ${GITHUB_WORKSPACE}/ThirdPartyLicenses/
            ${GITHUB_WORKSPACE}/ThirdPartyLicenses
            ${GITHUB_WORKSPACE}/README.md
            ${GITHUB_WORKSPACE}/CONTRIBUTORS.txt
                      
